### ISSUE TITLE
"Shutdown" + " and " +  "Restart" doesn't translate

### ISSUE THREAD

**Issue by juanlatorre** [jonnius/gnome-system-menu#10]
Hey, something is wrong on `extension.js` line 50.

`{ type: "powerOff",	   text: _("Power Off") + _(" and ") + _("Reboot"), action: ''}`

This text doesn't get translated, if I remove the concatenation and just keep one _("") it works, dunno how to make it work with multiple strings.

I tried different ways but it seems that Gettext doesn't work with string concatenation.

![Screenshot with the untranslated menu item](https://user-images.githubusercontent.com/4494526/97819644-a425c200-1c88-11eb-9454-b74bcfbd1098.png)

**Comment by jonnius** [comment]
I changed the English text to just `Reboot`. So now it translates fine. Thanks for reporting.

**Comment by jonnius** [comment]
Just pushed the changes. Update your language's po file from the pot file.
