### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by steelstring94** [jonnius/gnome-system-menu#2]
The readme contains no instructions, and compile.sh produces no output and does not appear to create any executable or makefile.  How is this supposed to be installed?

**Comment by jonnius** [comment]
Sorry for the missing readme. I added it along with an install script. Before it would has been as easy as:

- Rename the directory to match the uuid: SystemMenu@jonnius.github.com
- Move it to ~/.local/share/gnome-shell/extensions/SystemMenu@jonnius.github.com
- Run compile.sh inside the directory (creates translation template, compiles translation files and schemas)
- Restart the GNOME Shell and enable the extension using the GNOME Tweak Tool.
